import { StyleSheet } from 'react-native';

export const globalColors = {
    primary: '#ff2d95',
    secondary: '#3ecadd',
    tertiary: '#2b2d42',
    accent: '#8cc63f',
    success: '#8cc63f',
    warning: '#ff2d95',
    danger: '#e71d36',
    info: '#3ecadd',
    background: '#ffffff',
    surface: '#f8f9fa',
    card: '#ffffff',
    text: '#2b2d42',
    textSecondary: '#6c757d',
    border: '#e9ecef',
    disabled: '#adb5bd',
    placeholder: '#6c757d',
    backdrop: 'rgba(43, 45, 66, 0.5)',
    elevation: {
        level0: 'transparent',
        level1: '#ffffff',
        level2: '#ffffff',
        level3: '#ffffff',
        level4: '#ffffff',
        level5: '#ffffff',
    },
};

export const globalStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: globalColors.background,
    },
    primaryButton: {
        backgroundColor: globalColors.primary,
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
        width: '100%',
        alignItems: 'center',
        elevation: 2,
        shadowColor: globalColors.tertiary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    buttonText: {
        color: globalColors.background,
        fontSize: 18,
        fontWeight: '600',
    },
    secondaryButton: {
        backgroundColor: globalColors.secondary,
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
        width: '100%',
        alignItems: 'center',
        elevation: 2,
    },
    accentButton: {
        backgroundColor: globalColors.accent,
        borderRadius: 8,
        padding: 12,
        marginBottom: 10,
        width: '100%',
        alignItems: 'center',
        elevation: 2,
    },
});
